name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build pkg-config cmake g++ qt5-default qtbase5-dev qttools5-dev-tools

      # --- First build ---
      - name: Configure CMake
        run: cmake -B build -G "Ninja"

      - name: Build
        run: cmake --build build
